// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for Cuisine.
const (
	American Cuisine = "american"
	Asian    Cuisine = "asian"
	European Cuisine = "european"
	French   Cuisine = "french"
	Italian  Cuisine = "italian"
	Japanese Cuisine = "japanese"
	Russian  Cuisine = "russian"
)

// Valid indicates whether the value is a known member of the Cuisine enum.
func (e Cuisine) Valid() bool {
	switch e {
	case American:
		return true
	case Asian:
		return true
	case European:
		return true
	case French:
		return true
	case Italian:
		return true
	case Japanese:
		return true
	case Russian:
		return true
	default:
		return false
	}
}

// Defines values for FieldViolationReason.
const (
	InvalidFormat    FieldViolationReason = "invalid_format"
	NotUnique        FieldViolationReason = "not_unique"
	OutOfRange       FieldViolationReason = "out_of_range"
	Required         FieldViolationReason = "required"
	TooLong          FieldViolationReason = "too_long"
	TooShort         FieldViolationReason = "too_short"
	UnsupportedValue FieldViolationReason = "unsupported_value"
)

// Valid indicates whether the value is a known member of the FieldViolationReason enum.
func (e FieldViolationReason) Valid() bool {
	switch e {
	case InvalidFormat:
		return true
	case NotUnique:
		return true
	case OutOfRange:
		return true
	case Required:
		return true
	case TooLong:
		return true
	case TooShort:
		return true
	case UnsupportedValue:
		return true
	default:
		return false
	}
}

// Defines values for FulfillmentType.
const (
	Delivery FulfillmentType = "delivery"
	DineIn   FulfillmentType = "dine_in"
	Pickup   FulfillmentType = "pickup"
)

// Valid indicates whether the value is a known member of the FulfillmentType enum.
func (e FulfillmentType) Valid() bool {
	switch e {
	case Delivery:
		return true
	case DineIn:
		return true
	case Pickup:
		return true
	default:
		return false
	}
}

// Defines values for MessageRole.
const (
	Assistant MessageRole = "assistant"
	User      MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for OrderStatus.
const (
	Accepted   OrderStatus = "accepted"
	Cancelled  OrderStatus = "cancelled"
	Closed     OrderStatus = "closed"
	Cooking    OrderStatus = "cooking"
	InDelivery OrderStatus = "in_delivery"
	Ready      OrderStatus = "ready"
)

// Valid indicates whether the value is a known member of the OrderStatus enum.
func (e OrderStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Cancelled:
		return true
	case Closed:
		return true
	case Cooking:
		return true
	case InDelivery:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for PaymentMethod.
const (
	OnDelivery PaymentMethod = "on_delivery"
	OnlineStub PaymentMethod = "online_stub"
)

// Valid indicates whether the value is a known member of the PaymentMethod enum.
func (e PaymentMethod) Valid() bool {
	switch e {
	case OnDelivery:
		return true
	case OnlineStub:
		return true
	default:
		return false
	}
}

// Defines values for SessionInfoRole.
const (
	Admin    SessionInfoRole = "admin"
	Customer SessionInfoRole = "customer"
	Guest    SessionInfoRole = "guest"
)

// Valid indicates whether the value is a known member of the SessionInfoRole enum.
func (e SessionInfoRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Customer:
		return true
	case Guest:
		return true
	default:
		return false
	}
}

// AddCartItemRequest defines model for AddCartItemRequest.
type AddCartItemRequest struct {
	DishId   int     `json:"dish_id"`
	Note     *string `json:"note,omitempty"`
	Quantity int     `json:"quantity"`
}

// AnalyticsOverview defines model for AnalyticsOverview.
type AnalyticsOverview struct {
	// ConversionRate query → order ratio
	ConversionRate       *float32  `json:"conversion_rate,omitempty"`
	PeriodFrom           time.Time `json:"period_from"`
	PeriodTo             time.Time `json:"period_to"`
	TopAllergensExcluded *[]struct {
		Code  string `json:"code"`
		Count int    `json:"count"`
	} `json:"top_allergens_excluded,omitempty"`
	TopDishes *[]struct {
		Count  int    `json:"count"`
		DishId int    `json:"dish_id"`
		Name   string `json:"name"`
	} `json:"top_dishes,omitempty"`
	TotalOrders  *int `json:"total_orders,omitempty"`
	TotalQueries *int `json:"total_queries,omitempty"`
	TotalUsers   *int `json:"total_users,omitempty"`
}

// Cart defines model for Cart.
type Cart struct {
	Items    []CartItem    `json:"items"`
	Total    string        `json:"total"`
	Warnings []CartWarning `json:"warnings"`
}

// CartItem defines model for CartItem.
type CartItem struct {
	AddedAt   *time.Time `json:"added_at,omitempty"`
	Available bool       `json:"available"`
	DishId    int        `json:"dish_id"`
	LineTotal string     `json:"line_total"`
	Name      string     `json:"name"`
	Note      *string    `json:"note,omitempty"`
	Price     string     `json:"price"`
	Quantity  int        `json:"quantity"`
	SortOrder int        `json:"sort_order"`
}

// CartWarning defines model for CartWarning.
type CartWarning struct {
	Code   string `json:"code"`
	DishId int    `json:"dish_id"`
}

// Category defines model for Category.
type Category struct {
	Id          int    `json:"id"`
	IsAvailable bool   `json:"is_available"`
	Name        string `json:"name"`
	SortOrder   int    `json:"sort_order"`
}

// CategoryList defines model for CategoryList.
type CategoryList struct {
	Items []Category `json:"items"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// Chat defines model for Chat.
type Chat struct {
	CreatedAt     time.Time          `json:"created_at"`
	Id            openapi_types.UUID `json:"id"`
	LastMessageAt time.Time          `json:"last_message_at"`
	Title         string             `json:"title"`
	UserId        openapi_types.UUID `json:"user_id"`
}

// ChatList defines model for ChatList.
type ChatList struct {
	Items  []Chat `json:"items"`
	Limit  int    `json:"limit"`
	Offset int    `json:"offset"`
	Total  int    `json:"total"`
}

// ChatWithMessages defines model for ChatWithMessages.
type ChatWithMessages struct {
	Chat Chat `json:"chat"`

	// HasMore Есть ли ещё более старые сообщения
	HasMore *bool `json:"has_more,omitempty"`

	// Messages Сортировка — по created_at ASC (старые → новые)
	Messages []Message `json:"messages"`
}

// CreateCategoryRequest defines model for CreateCategoryRequest.
type CreateCategoryRequest struct {
	IsAvailable *bool  `json:"is_available,omitempty"`
	Name        string `json:"name"`
	SortOrder   *int   `json:"sort_order,omitempty"`
}

// CreateChatRequest defines model for CreateChatRequest.
type CreateChatRequest struct {
	Title *string `json:"title,omitempty"`
}

// CreateDishRequest defines model for CreateDishRequest.
type CreateDishRequest struct {
	Allergens      *[]string `json:"allergens,omitempty"`
	CaloriesKcal   *int      `json:"calories_kcal,omitempty"`
	CarbsG         *float32  `json:"carbs_g,omitempty"`
	CategoryId     int       `json:"category_id"`
	Composition    *string   `json:"composition,omitempty"`
	Cuisine        Cuisine   `json:"cuisine"`
	Currency       *string   `json:"currency,omitempty"`
	Description    *string   `json:"description,omitempty"`
	Dietary        *[]string `json:"dietary,omitempty"`
	FatG           *float32  `json:"fat_g,omitempty"`
	ImageUrl       *string   `json:"image_url,omitempty"`
	IsAvailable    *bool     `json:"is_available,omitempty"`
	Name           string    `json:"name"`
	PortionWeightG *int      `json:"portion_weight_g,omitempty"`
	PriceMinor     int       `json:"price_minor"`
	ProteinG       *float32  `json:"protein_g,omitempty"`
	TagIds         *[]int    `json:"tag_ids,omitempty"`
}

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	DeliveryAddress *string         `json:"delivery_address,omitempty"`
	DeliveryNotes   *string         `json:"delivery_notes,omitempty"`
	FulfillmentType FulfillmentType `json:"fulfillment_type"`
	Notes           *string         `json:"notes,omitempty"`
	PaymentMethod   PaymentMethod   `json:"payment_method"`
}

// CreateTagRequest defines model for CreateTagRequest.
type CreateTagRequest struct {
	Color *string `json:"color,omitempty"`
	Name  string  `json:"name"`
	Slug  string  `json:"slug"`
}

// Cuisine defines model for Cuisine.
type Cuisine string

// Dish defines model for Dish.
type Dish struct {
	Allergens      []string `json:"allergens"`
	CaloriesKcal   *int     `json:"calories_kcal,omitempty"`
	CarbsG         *float32 `json:"carbs_g,omitempty"`
	CategoryId     int      `json:"category_id"`
	Composition    string   `json:"composition"`
	Cuisine        Cuisine  `json:"cuisine"`
	Currency       string   `json:"currency"`
	Description    string   `json:"description"`
	Dietary        []string `json:"dietary"`
	FatG           *float32 `json:"fat_g,omitempty"`
	Id             int      `json:"id"`
	ImageUrl       string   `json:"image_url"`
	IsAvailable    bool     `json:"is_available"`
	Name           string   `json:"name"`
	PortionWeightG *int     `json:"portion_weight_g,omitempty"`
	PriceMinor     int      `json:"price_minor"`
	ProteinG       *float32 `json:"protein_g,omitempty"`
	Tags           []Tag    `json:"tags"`
}

// DishList defines model for DishList.
type DishList struct {
	Items  []Dish `json:"items"`
	Limit  int    `json:"limit"`
	Offset int    `json:"offset"`
	Total  int    `json:"total"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string               `json:"code"`
		Details *Error_Error_Details `json:"details,omitempty"`
		Message string               `json:"message"`
	} `json:"error"`
}

// Error_Error_Details defines model for Error.Error.Details.
type Error_Error_Details struct {
	Fields               *[]FieldViolation      `json:"fields,omitempty"`
	TraceId              *string                `json:"trace_id,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// FieldViolation defines model for FieldViolation.
type FieldViolation struct {
	Max    *FieldViolation_Max  `json:"max,omitempty"`
	Min    *FieldViolation_Min  `json:"min,omitempty"`
	Name   string               `json:"name"`
	Reason FieldViolationReason `json:"reason"`
}

// FieldViolationMax0 defines model for .
type FieldViolationMax0 = int

// FieldViolationMax1 defines model for .
type FieldViolationMax1 = float32

// FieldViolationMax2 defines model for .
type FieldViolationMax2 = string

// FieldViolation_Max defines model for FieldViolation.Max.
type FieldViolation_Max struct {
	union json.RawMessage
}

// FieldViolationMin0 defines model for .
type FieldViolationMin0 = int

// FieldViolationMin1 defines model for .
type FieldViolationMin1 = float32

// FieldViolationMin2 defines model for .
type FieldViolationMin2 = string

// FieldViolation_Min defines model for FieldViolation.Min.
type FieldViolation_Min struct {
	union json.RawMessage
}

// FieldViolationReason defines model for FieldViolation.Reason.
type FieldViolationReason string

// FulfillmentType defines model for FulfillmentType.
type FulfillmentType string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Message defines model for Message.
type Message struct {
	ChatId             openapi_types.UUID `json:"chat_id"`
	Content            string             `json:"content"`
	CreatedAt          time.Time          `json:"created_at"`
	Id                 openapi_types.UUID `json:"id"`
	RecommendedDishIds *[]int             `json:"recommended_dish_ids,omitempty"`
	Role               MessageRole        `json:"role"`
}

// MessageRole defines model for MessageRole.
type MessageRole string

// Order defines model for Order.
type Order struct {
	CreatedAt         time.Time            `json:"created_at"`
	CustomerEmail     *openapi_types.Email `json:"customer_email,omitempty"`
	CustomerFirstName string               `json:"customer_first_name"`
	CustomerLastName  string               `json:"customer_last_name"`
	CustomerPhone     string               `json:"customer_phone"`
	DeliveryAddress   *string              `json:"delivery_address,omitempty"`
	DeliveryNotes     *string              `json:"delivery_notes,omitempty"`
	FulfillmentType   FulfillmentType      `json:"fulfillment_type"`
	Id                openapi_types.UUID   `json:"id"`
	Items             []OrderItem          `json:"items"`
	Notes             *string              `json:"notes,omitempty"`
	PaymentMethod     PaymentMethod        `json:"payment_method"`
	Status            OrderStatus          `json:"status"`
	Total             string               `json:"total"`
	UpdatedAt         time.Time            `json:"updated_at"`
	UserId            openapi_types.UUID   `json:"user_id"`
}

// OrderItem defines model for OrderItem.
type OrderItem struct {
	DishId    *int   `json:"dish_id"`
	DishName  string `json:"dish_name"`
	DishPrice string `json:"dish_price"`
	LineTotal string `json:"line_total"`
	Quantity  int    `json:"quantity"`
	SortOrder int    `json:"sort_order"`
}

// OrderList defines model for OrderList.
type OrderList struct {
	Items  []Order `json:"items"`
	Limit  int     `json:"limit"`
	Offset int     `json:"offset"`
	Total  int     `json:"total"`
}

// OrderStatus defines model for OrderStatus.
type OrderStatus string

// PatchCartItemRequest defines model for PatchCartItemRequest.
type PatchCartItemRequest struct {
	Note      *string `json:"note,omitempty"`
	Quantity  *int    `json:"quantity,omitempty"`
	SortOrder *int    `json:"sort_order,omitempty"`
}

// PatchCategoryRequest defines model for PatchCategoryRequest.
type PatchCategoryRequest struct {
	IsAvailable *bool   `json:"is_available,omitempty"`
	Name        *string `json:"name,omitempty"`
	SortOrder   *int    `json:"sort_order,omitempty"`
}

// PatchDishRequest defines model for PatchDishRequest.
type PatchDishRequest struct {
	Allergens      *[]string `json:"allergens,omitempty"`
	CaloriesKcal   *int      `json:"calories_kcal,omitempty"`
	CarbsG         *float32  `json:"carbs_g,omitempty"`
	CategoryId     *int      `json:"category_id,omitempty"`
	Composition    *string   `json:"composition,omitempty"`
	Cuisine        *Cuisine  `json:"cuisine,omitempty"`
	Currency       *string   `json:"currency,omitempty"`
	Description    *string   `json:"description,omitempty"`
	Dietary        *[]string `json:"dietary,omitempty"`
	FatG           *float32  `json:"fat_g,omitempty"`
	ImageUrl       *string   `json:"image_url,omitempty"`
	IsAvailable    *bool     `json:"is_available,omitempty"`
	Name           *string   `json:"name,omitempty"`
	PortionWeightG *int      `json:"portion_weight_g,omitempty"`
	PriceMinor     *int      `json:"price_minor,omitempty"`
	ProteinG       *float32  `json:"protein_g,omitempty"`
	TagIds         *[]int    `json:"tag_ids,omitempty"`
}

// PatchOrderStatusRequest defines model for PatchOrderStatusRequest.
type PatchOrderStatusRequest struct {
	Note   *string     `json:"note,omitempty"`
	Status OrderStatus `json:"status"`
}

// PatchProfileRequest defines model for PatchProfileRequest.
type PatchProfileRequest struct {
	Allergens *[]string `json:"allergens,omitempty"`
	Dietary   *[]string `json:"dietary,omitempty"`
	FirstName *string   `json:"first_name,omitempty"`
	LastName  *string   `json:"last_name,omitempty"`
	Phone     *string   `json:"phone,omitempty"`
}

// PatchTagRequest defines model for PatchTagRequest.
type PatchTagRequest struct {
	Color *string `json:"color,omitempty"`
	Name  *string `json:"name,omitempty"`
	Slug  *string `json:"slug,omitempty"`
}

// PaymentMethod defines model for PaymentMethod.
type PaymentMethod string

// Profile defines model for Profile.
type Profile struct {
	// Allergens allergen codes
	Allergens []string `json:"allergens"`

	// Dietary dietary codes
	Dietary   []string            `json:"dietary"`
	Email     openapi_types.Email `json:"email"`
	FirstName *string             `json:"first_name,omitempty"`
	LastName  *string             `json:"last_name,omitempty"`

	// Phone E.164
	Phone *string `json:"phone,omitempty"`
}

// QueryEvent defines model for QueryEvent.
type QueryEvent struct {
	ChatId            *openapi_types.UUID `json:"chat_id,omitempty"`
	CreatedAt         time.Time           `json:"created_at"`
	DetectedAllergens *[]string           `json:"detected_allergens,omitempty"`
	DetectedDietary   *[]string           `json:"detected_dietary,omitempty"`
	Id                openapi_types.UUID  `json:"id"`
	RecommendedIds    *[]int              `json:"recommended_ids,omitempty"`
	Text              string              `json:"text"`
	UserId            openapi_types.UUID  `json:"user_id"`
}

// QueryEventList defines model for QueryEventList.
type QueryEventList struct {
	Items  []QueryEvent `json:"items"`
	Limit  int          `json:"limit"`
	Offset int          `json:"offset"`
	Total  int          `json:"total"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// SendMessageRequest defines model for SendMessageRequest.
type SendMessageRequest struct {
	Content string `json:"content"`
}

// SessionInfo defines model for SessionInfo.
type SessionInfo struct {
	Csrf    string           `json:"csrf"`
	IsGuest bool             `json:"is_guest"`
	Role    *SessionInfoRole `json:"role,omitempty"`

	// UserId null если ещё не было стейтфул-действий — PG-строки пользователя пока нет
	UserId *openapi_types.UUID `json:"user_id,omitempty"`
}

// SessionInfoRole defines model for SessionInfo.Role.
type SessionInfoRole string

// Tag defines model for Tag.
type Tag struct {
	// Color hex, например #E53935
	Color string `json:"color"`
	Id    int    `json:"id"`
	Name  string `json:"name"`
	Slug  string `json:"slug"`
}

// TagList defines model for TagList.
type TagList struct {
	Items []Tag `json:"items"`
}

// CSRFToken defines model for CSRFToken.
type CSRFToken = string

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// PathDishID defines model for PathDishID.
type PathDishID = int

// PathID defines model for PathID.
type PathID = openapi_types.UUID

// PathIntID defines model for PathIntID.
type PathIntID = int

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// AdminGetAnalyticsOverviewParams defines parameters for AdminGetAnalyticsOverview.
type AdminGetAnalyticsOverviewParams struct {
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`
	To   *time.Time `form:"to,omitempty" json:"to,omitempty"`
}

// AdminListAnalyticsQueriesParams defines parameters for AdminListAnalyticsQueries.
type AdminListAnalyticsQueriesParams struct {
	From   *time.Time `form:"from,omitempty" json:"from,omitempty"`
	To     *time.Time `form:"to,omitempty" json:"to,omitempty"`
	Limit  *Limit     `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset    `form:"offset,omitempty" json:"offset,omitempty"`
}

// AdminCreateCategoryParams defines parameters for AdminCreateCategory.
type AdminCreateCategoryParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminDeleteCategoryParams defines parameters for AdminDeleteCategory.
type AdminDeleteCategoryParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminUpdateCategoryParams defines parameters for AdminUpdateCategory.
type AdminUpdateCategoryParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminCreateDishParams defines parameters for AdminCreateDish.
type AdminCreateDishParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminDeleteDishParams defines parameters for AdminDeleteDish.
type AdminDeleteDishParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminUpdateDishParams defines parameters for AdminUpdateDish.
type AdminUpdateDishParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminUploadDishImageMultipartBody defines parameters for AdminUploadDishImage.
type AdminUploadDishImageMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// AdminUploadDishImageParams defines parameters for AdminUploadDishImage.
type AdminUploadDishImageParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminListOrdersParams defines parameters for AdminListOrders.
type AdminListOrdersParams struct {
	Status *OrderStatus        `form:"status,omitempty" json:"status,omitempty"`
	From   *time.Time          `form:"from,omitempty" json:"from,omitempty"`
	To     *time.Time          `form:"to,omitempty" json:"to,omitempty"`
	UserId *openapi_types.UUID `form:"user_id,omitempty" json:"user_id,omitempty"`
	Limit  *Limit              `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset             `form:"offset,omitempty" json:"offset,omitempty"`
}

// AdminUpdateOrderStatusParams defines parameters for AdminUpdateOrderStatus.
type AdminUpdateOrderStatusParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminCreateTagParams defines parameters for AdminCreateTag.
type AdminCreateTagParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminDeleteTagParams defines parameters for AdminDeleteTag.
type AdminDeleteTagParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminUpdateTagParams defines parameters for AdminUpdateTag.
type AdminUpdateTagParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// LoginParams defines parameters for Login.
type LoginParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// LogoutParams defines parameters for Logout.
type LogoutParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ChangePasswordParams defines parameters for ChangePassword.
type ChangePasswordParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// RegisterParams defines parameters for Register.
type RegisterParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ClearCartParams defines parameters for ClearCart.
type ClearCartParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AddCartItemParams defines parameters for AddCartItem.
type AddCartItemParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// RemoveCartItemParams defines parameters for RemoveCartItem.
type RemoveCartItemParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// UpdateCartItemParams defines parameters for UpdateCartItem.
type UpdateCartItemParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListChatsParams defines parameters for ListChats.
type ListChatsParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateChatParams defines parameters for CreateChat.
type CreateChatParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// DeleteChatParams defines parameters for DeleteChat.
type DeleteChatParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// GetChatParams defines parameters for GetChat.
type GetChatParams struct {
	MessagesLimit *int `form:"messages_limit,omitempty" json:"messages_limit,omitempty"`

	// MessagesBefore cursor — id сообщения, до которого подгружаем
	MessagesBefore *openapi_types.UUID `form:"messages_before,omitempty" json:"messages_before,omitempty"`
}

// SendMessageParams defines parameters for SendMessage.
type SendMessageParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListDishesParams defines parameters for ListDishes.
type ListDishesParams struct {
	CategoryId *int `form:"category_id,omitempty" json:"category_id,omitempty"`

	// Available по умолчанию true; false вернёт всё включая стоп-лист
	Available *bool `form:"available,omitempty" json:"available,omitempty"`

	// Q поиск по названию
	Q                *string   `form:"q,omitempty" json:"q,omitempty"`
	ExcludeAllergens *[]string `form:"exclude_allergens,omitempty" json:"exclude_allergens,omitempty"`
	Dietary          *[]string `form:"dietary,omitempty" json:"dietary,omitempty"`
	TagIds           *[]int    `form:"tag_ids,omitempty" json:"tag_ids,omitempty"`
	Limit            *Limit    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset           *Offset   `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListOrdersParams defines parameters for ListOrders.
type ListOrdersParams struct {
	Status *OrderStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *Limit       `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset      `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateOrderParams defines parameters for CreateOrder.
type CreateOrderParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// UpdateProfileParams defines parameters for UpdateProfile.
type UpdateProfileParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminCreateCategoryJSONRequestBody defines body for AdminCreateCategory for application/json ContentType.
type AdminCreateCategoryJSONRequestBody = CreateCategoryRequest

// AdminUpdateCategoryJSONRequestBody defines body for AdminUpdateCategory for application/json ContentType.
type AdminUpdateCategoryJSONRequestBody = PatchCategoryRequest

// AdminCreateDishJSONRequestBody defines body for AdminCreateDish for application/json ContentType.
type AdminCreateDishJSONRequestBody = CreateDishRequest

// AdminUpdateDishJSONRequestBody defines body for AdminUpdateDish for application/json ContentType.
type AdminUpdateDishJSONRequestBody = PatchDishRequest

// AdminUploadDishImageMultipartRequestBody defines body for AdminUploadDishImage for multipart/form-data ContentType.
type AdminUploadDishImageMultipartRequestBody AdminUploadDishImageMultipartBody

// AdminUpdateOrderStatusJSONRequestBody defines body for AdminUpdateOrderStatus for application/json ContentType.
type AdminUpdateOrderStatusJSONRequestBody = PatchOrderStatusRequest

// AdminCreateTagJSONRequestBody defines body for AdminCreateTag for application/json ContentType.
type AdminCreateTagJSONRequestBody = CreateTagRequest

// AdminUpdateTagJSONRequestBody defines body for AdminUpdateTag for application/json ContentType.
type AdminUpdateTagJSONRequestBody = PatchTagRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// AddCartItemJSONRequestBody defines body for AddCartItem for application/json ContentType.
type AddCartItemJSONRequestBody = AddCartItemRequest

// UpdateCartItemJSONRequestBody defines body for UpdateCartItem for application/json ContentType.
type UpdateCartItemJSONRequestBody = PatchCartItemRequest

// CreateChatJSONRequestBody defines body for CreateChat for application/json ContentType.
type CreateChatJSONRequestBody = CreateChatRequest

// SendMessageJSONRequestBody defines body for SendMessage for application/json ContentType.
type SendMessageJSONRequestBody = SendMessageRequest

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrderRequest

// UpdateProfileJSONRequestBody defines body for UpdateProfile for application/json ContentType.
type UpdateProfileJSONRequestBody = PatchProfileRequest

// Getter for additional properties for Error_Error_Details. Returns the specified
// element and whether it was found
func (a Error_Error_Details) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Error_Error_Details
func (a *Error_Error_Details) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Error_Error_Details to handle AdditionalProperties
func (a *Error_Error_Details) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["fields"]; found {
		err = json.Unmarshal(raw, &a.Fields)
		if err != nil {
			return fmt.Errorf("error reading 'fields': %w", err)
		}
		delete(object, "fields")
	}

	if raw, found := object["trace_id"]; found {
		err = json.Unmarshal(raw, &a.TraceId)
		if err != nil {
			return fmt.Errorf("error reading 'trace_id': %w", err)
		}
		delete(object, "trace_id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Error_Error_Details to handle AdditionalProperties
func (a Error_Error_Details) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Fields != nil {
		object["fields"], err = json.Marshal(a.Fields)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fields': %w", err)
		}
	}

	if a.TraceId != nil {
		object["trace_id"], err = json.Marshal(a.TraceId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'trace_id': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsFieldViolationMax0 returns the union data inside the FieldViolation_Max as a FieldViolationMax0
func (t FieldViolation_Max) AsFieldViolationMax0() (FieldViolationMax0, error) {
	var body FieldViolationMax0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFieldViolationMax0 overwrites any union data inside the FieldViolation_Max as the provided FieldViolationMax0
func (t *FieldViolation_Max) FromFieldViolationMax0(v FieldViolationMax0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFieldViolationMax0 performs a merge with any union data inside the FieldViolation_Max, using the provided FieldViolationMax0
func (t *FieldViolation_Max) MergeFieldViolationMax0(v FieldViolationMax0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFieldViolationMax1 returns the union data inside the FieldViolation_Max as a FieldViolationMax1
func (t FieldViolation_Max) AsFieldViolationMax1() (FieldViolationMax1, error) {
	var body FieldViolationMax1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFieldViolationMax1 overwrites any union data inside the FieldViolation_Max as the provided FieldViolationMax1
func (t *FieldViolation_Max) FromFieldViolationMax1(v FieldViolationMax1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFieldViolationMax1 performs a merge with any union data inside the FieldViolation_Max, using the provided FieldViolationMax1
func (t *FieldViolation_Max) MergeFieldViolationMax1(v FieldViolationMax1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFieldViolationMax2 returns the union data inside the FieldViolation_Max as a FieldViolationMax2
func (t FieldViolation_Max) AsFieldViolationMax2() (FieldViolationMax2, error) {
	var body FieldViolationMax2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFieldViolationMax2 overwrites any union data inside the FieldViolation_Max as the provided FieldViolationMax2
func (t *FieldViolation_Max) FromFieldViolationMax2(v FieldViolationMax2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFieldViolationMax2 performs a merge with any union data inside the FieldViolation_Max, using the provided FieldViolationMax2
func (t *FieldViolation_Max) MergeFieldViolationMax2(v FieldViolationMax2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t FieldViolation_Max) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *FieldViolation_Max) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsFieldViolationMin0 returns the union data inside the FieldViolation_Min as a FieldViolationMin0
func (t FieldViolation_Min) AsFieldViolationMin0() (FieldViolationMin0, error) {
	var body FieldViolationMin0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFieldViolationMin0 overwrites any union data inside the FieldViolation_Min as the provided FieldViolationMin0
func (t *FieldViolation_Min) FromFieldViolationMin0(v FieldViolationMin0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFieldViolationMin0 performs a merge with any union data inside the FieldViolation_Min, using the provided FieldViolationMin0
func (t *FieldViolation_Min) MergeFieldViolationMin0(v FieldViolationMin0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFieldViolationMin1 returns the union data inside the FieldViolation_Min as a FieldViolationMin1
func (t FieldViolation_Min) AsFieldViolationMin1() (FieldViolationMin1, error) {
	var body FieldViolationMin1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFieldViolationMin1 overwrites any union data inside the FieldViolation_Min as the provided FieldViolationMin1
func (t *FieldViolation_Min) FromFieldViolationMin1(v FieldViolationMin1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFieldViolationMin1 performs a merge with any union data inside the FieldViolation_Min, using the provided FieldViolationMin1
func (t *FieldViolation_Min) MergeFieldViolationMin1(v FieldViolationMin1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFieldViolationMin2 returns the union data inside the FieldViolation_Min as a FieldViolationMin2
func (t FieldViolation_Min) AsFieldViolationMin2() (FieldViolationMin2, error) {
	var body FieldViolationMin2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFieldViolationMin2 overwrites any union data inside the FieldViolation_Min as the provided FieldViolationMin2
func (t *FieldViolation_Min) FromFieldViolationMin2(v FieldViolationMin2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFieldViolationMin2 performs a merge with any union data inside the FieldViolation_Min, using the provided FieldViolationMin2
func (t *FieldViolation_Min) MergeFieldViolationMin2(v FieldViolationMin2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t FieldViolation_Min) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *FieldViolation_Min) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
