// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for AddCartItemRequestSource.
const (
	AddCartItemRequestSourceCart  AddCartItemRequestSource = "cart"
	AddCartItemRequestSourceChat  AddCartItemRequestSource = "chat"
	AddCartItemRequestSourceMenu  AddCartItemRequestSource = "menu"
	AddCartItemRequestSourceOther AddCartItemRequestSource = "other"
)

// Valid indicates whether the value is a known member of the AddCartItemRequestSource enum.
func (e AddCartItemRequestSource) Valid() bool {
	switch e {
	case AddCartItemRequestSourceCart:
		return true
	case AddCartItemRequestSourceChat:
		return true
	case AddCartItemRequestSourceMenu:
		return true
	case AddCartItemRequestSourceOther:
		return true
	default:
		return false
	}
}

// Defines values for AdminActionTarget.
const (
	AdminActionTargetCategory AdminActionTarget = "category"
	AdminActionTargetDish     AdminActionTarget = "dish"
	AdminActionTargetOrder    AdminActionTarget = "order"
	AdminActionTargetPrompt   AdminActionTarget = "prompt"
	AdminActionTargetTag      AdminActionTarget = "tag"
)

// Valid indicates whether the value is a known member of the AdminActionTarget enum.
func (e AdminActionTarget) Valid() bool {
	switch e {
	case AdminActionTargetCategory:
		return true
	case AdminActionTargetDish:
		return true
	case AdminActionTargetOrder:
		return true
	case AdminActionTargetPrompt:
		return true
	case AdminActionTargetTag:
		return true
	default:
		return false
	}
}

// Defines values for AdminActionVerb.
const (
	Create       AdminActionVerb = "create"
	Delete       AdminActionVerb = "delete"
	Publish      AdminActionVerb = "publish"
	Rollback     AdminActionVerb = "rollback"
	StatusChange AdminActionVerb = "status_change"
	Update       AdminActionVerb = "update"
)

// Valid indicates whether the value is a known member of the AdminActionVerb enum.
func (e AdminActionVerb) Valid() bool {
	switch e {
	case Create:
		return true
	case Delete:
		return true
	case Publish:
		return true
	case Rollback:
		return true
	case StatusChange:
		return true
	case Update:
		return true
	default:
		return false
	}
}

// Defines values for AdminAnalyticsPeriod.
const (
	AdminAnalyticsPeriodMonth AdminAnalyticsPeriod = "month"
	AdminAnalyticsPeriodToday AdminAnalyticsPeriod = "today"
	AdminAnalyticsPeriodWeek  AdminAnalyticsPeriod = "week"
)

// Valid indicates whether the value is a known member of the AdminAnalyticsPeriod enum.
func (e AdminAnalyticsPeriod) Valid() bool {
	switch e {
	case AdminAnalyticsPeriodMonth:
		return true
	case AdminAnalyticsPeriodToday:
		return true
	case AdminAnalyticsPeriodWeek:
		return true
	default:
		return false
	}
}

// Defines values for AdminDashboardPeriod.
const (
	AdminDashboardPeriodMonth AdminDashboardPeriod = "month"
	AdminDashboardPeriodToday AdminDashboardPeriod = "today"
	AdminDashboardPeriodWeek  AdminDashboardPeriod = "week"
)

// Valid indicates whether the value is a known member of the AdminDashboardPeriod enum.
func (e AdminDashboardPeriod) Valid() bool {
	switch e {
	case AdminDashboardPeriodMonth:
		return true
	case AdminDashboardPeriodToday:
		return true
	case AdminDashboardPeriodWeek:
		return true
	default:
		return false
	}
}

// Defines values for CategoryRole.
const (
	Companion CategoryRole = "companion"
	Main      CategoryRole = "main"
	None      CategoryRole = "none"
)

// Valid indicates whether the value is a known member of the CategoryRole enum.
func (e CategoryRole) Valid() bool {
	switch e {
	case Companion:
		return true
	case Main:
		return true
	case None:
		return true
	default:
		return false
	}
}

// Defines values for Cuisine.
const (
	American Cuisine = "american"
	Asian    Cuisine = "asian"
	European Cuisine = "european"
	French   Cuisine = "french"
	Italian  Cuisine = "italian"
	Japanese Cuisine = "japanese"
	Russian  Cuisine = "russian"
)

// Valid indicates whether the value is a known member of the Cuisine enum.
func (e Cuisine) Valid() bool {
	switch e {
	case American:
		return true
	case Asian:
		return true
	case European:
		return true
	case French:
		return true
	case Italian:
		return true
	case Japanese:
		return true
	case Russian:
		return true
	default:
		return false
	}
}

// Defines values for FieldViolationReason.
const (
	InvalidFormat    FieldViolationReason = "invalid_format"
	NotUnique        FieldViolationReason = "not_unique"
	OutOfRange       FieldViolationReason = "out_of_range"
	Required         FieldViolationReason = "required"
	TooLong          FieldViolationReason = "too_long"
	TooShort         FieldViolationReason = "too_short"
	UnsupportedValue FieldViolationReason = "unsupported_value"
)

// Valid indicates whether the value is a known member of the FieldViolationReason enum.
func (e FieldViolationReason) Valid() bool {
	switch e {
	case InvalidFormat:
		return true
	case NotUnique:
		return true
	case OutOfRange:
		return true
	case Required:
		return true
	case TooLong:
		return true
	case TooShort:
		return true
	case UnsupportedValue:
		return true
	default:
		return false
	}
}

// Defines values for FulfillmentType.
const (
	Delivery FulfillmentType = "delivery"
	DineIn   FulfillmentType = "dine_in"
	Pickup   FulfillmentType = "pickup"
)

// Valid indicates whether the value is a known member of the FulfillmentType enum.
func (e FulfillmentType) Valid() bool {
	switch e {
	case Delivery:
		return true
	case DineIn:
		return true
	case Pickup:
		return true
	default:
		return false
	}
}

// Defines values for MessageRole.
const (
	Assistant MessageRole = "assistant"
	User      MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for OrderStatus.
const (
	Accepted   OrderStatus = "accepted"
	Cancelled  OrderStatus = "cancelled"
	Closed     OrderStatus = "closed"
	Cooking    OrderStatus = "cooking"
	InDelivery OrderStatus = "in_delivery"
	Ready      OrderStatus = "ready"
)

// Valid indicates whether the value is a known member of the OrderStatus enum.
func (e OrderStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Cancelled:
		return true
	case Closed:
		return true
	case Cooking:
		return true
	case InDelivery:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for PairingAxis.
const (
	Drink    PairingAxis = "drink"
	Occasion PairingAxis = "occasion"
	Role     PairingAxis = "role"
	Vibe     PairingAxis = "vibe"
)

// Valid indicates whether the value is a known member of the PairingAxis enum.
func (e PairingAxis) Valid() bool {
	switch e {
	case Drink:
		return true
	case Occasion:
		return true
	case Role:
		return true
	case Vibe:
		return true
	default:
		return false
	}
}

// Defines values for PaymentMethod.
const (
	OnDelivery PaymentMethod = "on_delivery"
	OnlineStub PaymentMethod = "online_stub"
)

// Valid indicates whether the value is a known member of the PaymentMethod enum.
func (e PaymentMethod) Valid() bool {
	switch e {
	case OnDelivery:
		return true
	case OnlineStub:
		return true
	default:
		return false
	}
}

// Defines values for SessionInfoRole.
const (
	Admin    SessionInfoRole = "admin"
	Customer SessionInfoRole = "customer"
	Guest    SessionInfoRole = "guest"
)

// Valid indicates whether the value is a known member of the SessionInfoRole enum.
func (e SessionInfoRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Customer:
		return true
	case Guest:
		return true
	default:
		return false
	}
}

// Defines values for AdminListActionsParamsTarget.
const (
	AdminListActionsParamsTargetCategory AdminListActionsParamsTarget = "category"
	AdminListActionsParamsTargetDish     AdminListActionsParamsTarget = "dish"
	AdminListActionsParamsTargetOrder    AdminListActionsParamsTarget = "order"
	AdminListActionsParamsTargetPrompt   AdminListActionsParamsTarget = "prompt"
	AdminListActionsParamsTargetTag      AdminListActionsParamsTarget = "tag"
)

// Valid indicates whether the value is a known member of the AdminListActionsParamsTarget enum.
func (e AdminListActionsParamsTarget) Valid() bool {
	switch e {
	case AdminListActionsParamsTargetCategory:
		return true
	case AdminListActionsParamsTargetDish:
		return true
	case AdminListActionsParamsTargetOrder:
		return true
	case AdminListActionsParamsTargetPrompt:
		return true
	case AdminListActionsParamsTargetTag:
		return true
	default:
		return false
	}
}

// Defines values for AdminGetAnalyticsParamsPeriod.
const (
	AdminGetAnalyticsParamsPeriodMonth AdminGetAnalyticsParamsPeriod = "month"
	AdminGetAnalyticsParamsPeriodToday AdminGetAnalyticsParamsPeriod = "today"
	AdminGetAnalyticsParamsPeriodWeek  AdminGetAnalyticsParamsPeriod = "week"
)

// Valid indicates whether the value is a known member of the AdminGetAnalyticsParamsPeriod enum.
func (e AdminGetAnalyticsParamsPeriod) Valid() bool {
	switch e {
	case AdminGetAnalyticsParamsPeriodMonth:
		return true
	case AdminGetAnalyticsParamsPeriodToday:
		return true
	case AdminGetAnalyticsParamsPeriodWeek:
		return true
	default:
		return false
	}
}

// Defines values for AdminGetDashboardParamsPeriod.
const (
	AdminGetDashboardParamsPeriodMonth AdminGetDashboardParamsPeriod = "month"
	AdminGetDashboardParamsPeriodToday AdminGetDashboardParamsPeriod = "today"
	AdminGetDashboardParamsPeriodWeek  AdminGetDashboardParamsPeriod = "week"
)

// Valid indicates whether the value is a known member of the AdminGetDashboardParamsPeriod enum.
func (e AdminGetDashboardParamsPeriod) Valid() bool {
	switch e {
	case AdminGetDashboardParamsPeriodMonth:
		return true
	case AdminGetDashboardParamsPeriodToday:
		return true
	case AdminGetDashboardParamsPeriodWeek:
		return true
	default:
		return false
	}
}

// AddCartItemRequest defines model for AddCartItemRequest.
type AddCartItemRequest struct {
	DishId int `json:"dish_id"`

	// MessageId id assistant-сообщения, из которого взято блюдо (опционально, только при source="chat").
	// Позволяет связать клик с конкретной рекомендацией для аналитики.
	MessageId *openapi_types.UUID `json:"message_id,omitempty"`
	Note      *string             `json:"note,omitempty"`
	Quantity  int                 `json:"quantity"`

	// Source Источник добавления — используется только для аналитики (cart_additions).
	// Не влияет на корзину. Если не передан — считается "other".
	// "chat" — добавление из карточки блюда в ответе ассистента;
	// "menu" — со страницы публичного меню;
	// "cart" — изменение в самой корзине;
	// "other" — fallback для старых клиентов.
	Source *AddCartItemRequestSource `json:"source,omitempty"`
}

// AddCartItemRequestSource Источник добавления — используется только для аналитики (cart_additions).
// Не влияет на корзину. Если не передан — считается "other".
// "chat" — добавление из карточки блюда в ответе ассистента;
// "menu" — со страницы публичного меню;
// "cart" — изменение в самой корзине;
// "other" — fallback для старых клиентов.
type AddCartItemRequestSource string

// AdminAction defines model for AdminAction.
type AdminAction struct {
	Admin     AdminActionAuthor   `json:"admin"`
	Changes   []AdminActionChange `json:"changes"`
	CreatedAt time.Time           `json:"created_at"`

	// Id стабильный id (bigserial→string)
	Id          string            `json:"id"`
	Target      AdminActionTarget `json:"target"`
	TargetId    string            `json:"target_id"`
	TargetLabel string            `json:"target_label"`
	Verb        AdminActionVerb   `json:"verb"`
}

// AdminActionAuthor defines model for AdminActionAuthor.
type AdminActionAuthor struct {
	DisplayName string               `json:"display_name"`
	Email       *openapi_types.Email `json:"email,omitempty"`

	// HasNamesake true, если в системе есть другой админ с таким же ФИО — фронт показывает email рядом
	HasNamesake bool                `json:"has_namesake"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
}

// AdminActionChange defines model for AdminActionChange.
type AdminActionChange struct {
	Field string  `json:"field"`
	From  *string `json:"from,omitempty"`
	To    *string `json:"to,omitempty"`
}

// AdminActionList defines model for AdminActionList.
type AdminActionList struct {
	Items  []AdminAction `json:"items"`
	Limit  int           `json:"limit"`
	Offset int           `json:"offset"`
	Total  int           `json:"total"`
}

// AdminActionTarget defines model for AdminActionTarget.
type AdminActionTarget string

// AdminActionVerb defines model for AdminActionVerb.
type AdminActionVerb string

// AdminAnalytics defines model for AdminAnalytics.
type AdminAnalytics struct {
	// AssistantMessages число assistant-ответов с рекомендациями
	AssistantMessages int `json:"assistant_messages"`

	// AvgAddedToCartPerMessage среднее количество рекомендованных блюд, добавленных в корзину из чата
	AvgAddedToCartPerMessage float32 `json:"avg_added_to_cart_per_message"`

	// AvgOrderedPerMessage среднее количество рекомендованных блюд, реально заказанных гостем
	AvgOrderedPerMessage float32              `json:"avg_ordered_per_message"`
	Period               AdminAnalyticsPeriod `json:"period"`
	TopRecommendedDishes []TopDishEntry       `json:"top_recommended_dishes"`
}

// AdminAnalyticsPeriod defines model for AdminAnalytics.Period.
type AdminAnalyticsPeriod string

// AdminChatSuggestion defines model for AdminChatSuggestion.
type AdminChatSuggestion struct {
	// ClicksCount Сколько раз гости кликали по подсказке
	ClicksCount int64  `json:"clicks_count"`
	Id          int    `json:"id"`
	IsActive    bool   `json:"is_active"`
	SortOrder   int    `json:"sort_order"`
	Text        string `json:"text"`
}

// AdminChatSuggestionList defines model for AdminChatSuggestionList.
type AdminChatSuggestionList struct {
	Items []AdminChatSuggestion `json:"items"`
}

// AdminDashboard defines model for AdminDashboard.
type AdminDashboard struct {
	// AverageCheckMinor средний чек в копейках
	AverageCheckMinor int `json:"average_check_minor"`

	// CartAdditionsFromChat из них — добавлений из карточки в ответе ассистента (source='chat')
	CartAdditionsFromChat int `json:"cart_additions_from_chat"`

	// CartAdditionsFromMenu из них — добавлений со страницы /menu (source='menu')
	CartAdditionsFromMenu int `json:"cart_additions_from_menu"`

	// CartAdditionsTotal всего «+» в корзину за период (все источники)
	CartAdditionsTotal int `json:"cart_additions_total"`

	// Orders количество заказов за период
	Orders         int                   `json:"orders"`
	OrdersByStatus []OrdersByStatusEntry `json:"orders_by_status"`
	Period         AdminDashboardPeriod  `json:"period"`

	// RevenueMinor выручка в копейках
	RevenueMinor int            `json:"revenue_minor"`
	TopDishes    []TopDishEntry `json:"top_dishes"`
}

// AdminDashboardPeriod defines model for AdminDashboard.Period.
type AdminDashboardPeriod string

// Cart defines model for Cart.
type Cart struct {
	Currency string     `json:"currency"`
	Items    []CartItem `json:"items"`

	// TotalMinor Сумма line_total_minor по доступным позициям
	TotalMinor int           `json:"total_minor"`
	Warnings   []CartWarning `json:"warnings"`
}

// CartItem defines model for CartItem.
type CartItem struct {
	AddedAt *time.Time `json:"added_at,omitempty"`

	// Available Доступно к заказу: блюдо ещё в меню и не на стоп-листе
	Available bool `json:"available"`
	DishId    int  `json:"dish_id"`

	// LineTotalMinor price_minor * quantity
	LineTotalMinor int     `json:"line_total_minor"`
	Name           string  `json:"name"`
	Note           *string `json:"note,omitempty"`

	// PriceMinor Цена единицы в минимальных единицах валюты (копейки для RUB)
	PriceMinor int `json:"price_minor"`
	Quantity   int `json:"quantity"`
	SortOrder  int `json:"sort_order"`
}

// CartWarning defines model for CartWarning.
type CartWarning struct {
	// Code Тип предупреждения: dish_unavailable | dish_removed
	Code   string `json:"code"`
	DishId int    `json:"dish_id"`
}

// Category defines model for Category.
type Category struct {
	Id          int    `json:"id"`
	IsAvailable bool   `json:"is_available"`
	Name        string `json:"name"`

	// Role Роль категории в RAG-пайплайне рекомендаций:
	// * `none`      — не участвует в diversify/companion-логике;
	// * `main`      — основная категория, для диверсификации main-выдачи;
	// * `companion` — сопровождение (соус/гарнир/десерт/напиток), по 1 блюду на запрос.
	Role      CategoryRole `json:"role"`
	SortOrder int          `json:"sort_order"`
}

// CategoryList defines model for CategoryList.
type CategoryList struct {
	Items []Category `json:"items"`
}

// CategoryRole Роль категории в RAG-пайплайне рекомендаций:
// * `none`      — не участвует в diversify/companion-логике;
// * `main`      — основная категория, для диверсификации main-выдачи;
// * `companion` — сопровождение (соус/гарнир/десерт/напиток), по 1 блюду на запрос.
type CategoryRole string

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// Chat defines model for Chat.
type Chat struct {
	CreatedAt     time.Time          `json:"created_at"`
	Id            openapi_types.UUID `json:"id"`
	LastMessageAt time.Time          `json:"last_message_at"`
	Title         *string            `json:"title,omitempty"`
	UserId        openapi_types.UUID `json:"user_id"`
}

// ChatList defines model for ChatList.
type ChatList struct {
	Items  []Chat `json:"items"`
	Limit  int    `json:"limit"`
	Offset int    `json:"offset"`
	Total  int    `json:"total"`
}

// ChatSuggestion defines model for ChatSuggestion.
type ChatSuggestion struct {
	Id   int    `json:"id"`
	Text string `json:"text"`
}

// ChatSuggestionList defines model for ChatSuggestionList.
type ChatSuggestionList struct {
	Items []ChatSuggestion `json:"items"`
}

// ChatWithMessages defines model for ChatWithMessages.
type ChatWithMessages struct {
	Chat Chat `json:"chat"`

	// HasMore Есть ли ещё более старые сообщения
	HasMore *bool `json:"has_more,omitempty"`

	// Messages Сортировка — по created_at ASC (старые → новые)
	Messages []Message `json:"messages"`
}

// CreateCategoryRequest defines model for CreateCategoryRequest.
type CreateCategoryRequest struct {
	IsAvailable *bool  `json:"is_available,omitempty"`
	Name        string `json:"name"`

	// Role Роль категории в RAG-пайплайне рекомендаций:
	// * `none`      — не участвует в diversify/companion-логике;
	// * `main`      — основная категория, для диверсификации main-выдачи;
	// * `companion` — сопровождение (соус/гарнир/десерт/напиток), по 1 блюду на запрос.
	Role      *CategoryRole `json:"role,omitempty"`
	SortOrder *int          `json:"sort_order,omitempty"`
}

// CreateChatRequest defines model for CreateChatRequest.
type CreateChatRequest struct {
	Title *string `json:"title,omitempty"`
}

// CreateChatSuggestionRequest defines model for CreateChatSuggestionRequest.
type CreateChatSuggestionRequest struct {
	IsActive  *bool  `json:"is_active,omitempty"`
	SortOrder *int   `json:"sort_order,omitempty"`
	Text      string `json:"text"`
}

// CreateDishRequest defines model for CreateDishRequest.
type CreateDishRequest struct {
	Allergens    *[]string `json:"allergens,omitempty"`
	CaloriesKcal *int      `json:"calories_kcal,omitempty"`
	CarbsG       *float32  `json:"carbs_g,omitempty"`
	CategoryId   int       `json:"category_id"`
	Composition  *string   `json:"composition,omitempty"`
	Cuisine      Cuisine   `json:"cuisine"`
	Currency     *string   `json:"currency,omitempty"`
	Description  *string   `json:"description,omitempty"`
	Dietary      *[]string `json:"dietary,omitempty"`
	FatG         *float32  `json:"fat_g,omitempty"`
	ImageUrl     *string   `json:"image_url,omitempty"`
	IsAvailable  *bool     `json:"is_available,omitempty"`
	Name         string    `json:"name"`

	// PairingTagSlugs Slug'и pairing-тегов из vocabulary GET /admin/pairing-tags
	PairingTagSlugs *[]string `json:"pairing_tag_slugs,omitempty"`
	PortionWeightG  *int      `json:"portion_weight_g,omitempty"`
	PriceMinor      int       `json:"price_minor"`
	ProteinG        *float32  `json:"protein_g,omitempty"`
	TagIds          *[]int    `json:"tag_ids,omitempty"`
}

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	DeliveryAddress *string         `json:"delivery_address,omitempty"`
	DeliveryNotes   *string         `json:"delivery_notes,omitempty"`
	FulfillmentType FulfillmentType `json:"fulfillment_type"`
	Notes           *string         `json:"notes,omitempty"`
	PaymentMethod   PaymentMethod   `json:"payment_method"`
}

// CreateTagRequest defines model for CreateTagRequest.
type CreateTagRequest struct {
	Color *string `json:"color,omitempty"`
	Name  string  `json:"name"`
	Slug  string  `json:"slug"`
}

// Cuisine defines model for Cuisine.
type Cuisine string

// DebugSearchRequest defines model for DebugSearchRequest.
type DebugSearchRequest struct {
	Limit *int `json:"limit,omitempty"`

	// Query Произвольный текст, который мы эмбедим и ищем top-N
	Query string `json:"query"`
}

// DebugSearchResponse defines model for DebugSearchResponse.
type DebugSearchResponse struct {
	Items []DishEmbeddingNeighbor `json:"items"`
}

// Dish defines model for Dish.
type Dish struct {
	Allergens    []string `json:"allergens"`
	CaloriesKcal *int     `json:"calories_kcal,omitempty"`
	CarbsG       *float32 `json:"carbs_g,omitempty"`
	CategoryId   int      `json:"category_id"`
	Composition  string   `json:"composition"`
	Cuisine      Cuisine  `json:"cuisine"`
	Currency     string   `json:"currency"`
	Description  string   `json:"description"`
	Dietary      []string `json:"dietary"`
	FatG         *float32 `json:"fat_g,omitempty"`
	Id           int      `json:"id"`
	ImageUrl     string   `json:"image_url"`
	IsAvailable  bool     `json:"is_available"`
	Name         string   `json:"name"`

	// PairingTags Теги-пейринги для обогащения embed-текста (axis: drink/occasion/role/vibe)
	PairingTags    []PairingTag `json:"pairing_tags"`
	PortionWeightG *int         `json:"portion_weight_g,omitempty"`
	PriceMinor     int          `json:"price_minor"`
	ProteinG       *float32     `json:"protein_g,omitempty"`
	Tags           []Tag        `json:"tags"`
}

// DishEmbeddingNeighbor defines model for DishEmbeddingNeighbor.
type DishEmbeddingNeighbor struct {
	CategoryName string `json:"category_name"`
	DishId       int    `json:"dish_id"`
	IsAvailable  bool   `json:"is_available"`
	Name         string `json:"name"`

	// Score Cosine-similarity (выше = ближе). Само блюдо в preview даёт ≈1.
	Score float32 `json:"score"`
}

// DishEmbeddingPreview defines model for DishEmbeddingPreview.
type DishEmbeddingPreview struct {
	DishId int `json:"dish_id"`

	// EmbedText Финальный текст, который ушёл в Cohere (после indexer.BuildEmbedText)
	EmbedText string `json:"embed_text"`

	// Neighbors Top-N ближайших точек в Qdrant (включая само блюдо со score≈1)
	Neighbors []DishEmbeddingNeighbor `json:"neighbors"`

	// VectorDim Размерность embedding-вектора
	VectorDim int `json:"vector_dim"`

	// VectorSample Первые 8 значений — sanity-check
	VectorSample []float32 `json:"vector_sample"`
}

// DishList defines model for DishList.
type DishList struct {
	Items  []Dish `json:"items"`
	Limit  int    `json:"limit"`
	Offset int    `json:"offset"`
	Total  int    `json:"total"`
}

// DishesReindexResult defines model for DishesReindexResult.
type DishesReindexResult struct {
	// Failed Сколько провалилось (логи в warn)
	Failed int `json:"failed"`

	// Indexed Сколько успешно эмбедированы и upserted
	Indexed int `json:"indexed"`

	// Total Сколько всего блюд обработано
	Total int `json:"total"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string               `json:"code"`
		Details *Error_Error_Details `json:"details,omitempty"`
		Message string               `json:"message"`
	} `json:"error"`
}

// Error_Error_Details defines model for Error.Error.Details.
type Error_Error_Details struct {
	Fields               *[]FieldViolation      `json:"fields,omitempty"`
	TraceId              *string                `json:"trace_id,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// FieldViolation defines model for FieldViolation.
type FieldViolation struct {
	Max    *FieldViolation_Max  `json:"max,omitempty"`
	Min    *FieldViolation_Min  `json:"min,omitempty"`
	Name   string               `json:"name"`
	Reason FieldViolationReason `json:"reason"`
}

// FieldViolationMax0 defines model for .
type FieldViolationMax0 = int

// FieldViolationMax1 defines model for .
type FieldViolationMax1 = float32

// FieldViolationMax2 defines model for .
type FieldViolationMax2 = string

// FieldViolation_Max defines model for FieldViolation.Max.
type FieldViolation_Max struct {
	union json.RawMessage
}

// FieldViolationMin0 defines model for .
type FieldViolationMin0 = int

// FieldViolationMin1 defines model for .
type FieldViolationMin1 = float32

// FieldViolationMin2 defines model for .
type FieldViolationMin2 = string

// FieldViolation_Min defines model for FieldViolation.Min.
type FieldViolation_Min struct {
	union json.RawMessage
}

// FieldViolationReason defines model for FieldViolation.Reason.
type FieldViolationReason string

// FulfillmentType defines model for FulfillmentType.
type FulfillmentType string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Message defines model for Message.
type Message struct {
	ChatId             openapi_types.UUID `json:"chat_id"`
	Content            string             `json:"content"`
	CreatedAt          time.Time          `json:"created_at"`
	Id                 openapi_types.UUID `json:"id"`
	RecommendedDishIds *[]int             `json:"recommended_dish_ids,omitempty"`
	Role               MessageRole        `json:"role"`
}

// MessageRole defines model for MessageRole.
type MessageRole string

// Order defines model for Order.
type Order struct {
	CreatedAt         time.Time            `json:"created_at"`
	Currency          string               `json:"currency"`
	CustomerEmail     *openapi_types.Email `json:"customer_email,omitempty"`
	CustomerFirstName string               `json:"customer_first_name"`
	CustomerLastName  string               `json:"customer_last_name"`
	CustomerPhone     string               `json:"customer_phone"`
	DeliveryAddress   *string              `json:"delivery_address,omitempty"`
	DeliveryNotes     *string              `json:"delivery_notes,omitempty"`
	FulfillmentType   FulfillmentType      `json:"fulfillment_type"`
	Id                openapi_types.UUID   `json:"id"`
	Items             []OrderItem          `json:"items"`
	Notes             *string              `json:"notes,omitempty"`
	PaymentMethod     PaymentMethod        `json:"payment_method"`
	Status            OrderStatus          `json:"status"`
	TotalMinor        int                  `json:"total_minor"`
	UpdatedAt         time.Time            `json:"updated_at"`
	UserId            openapi_types.UUID   `json:"user_id"`
}

// OrderItem defines model for OrderItem.
type OrderItem struct {
	// DishId null если блюдо удалено из меню после оформления
	DishId *int `json:"dish_id"`

	// DishName Snapshot названия на момент заказа
	DishName string `json:"dish_name"`

	// DishPriceMinor Snapshot цены за единицу в копейках
	DishPriceMinor int `json:"dish_price_minor"`
	LineTotalMinor int `json:"line_total_minor"`
	Quantity       int `json:"quantity"`
	SortOrder      int `json:"sort_order"`
}

// OrderList defines model for OrderList.
type OrderList struct {
	Items  []Order `json:"items"`
	Limit  int     `json:"limit"`
	Offset int     `json:"offset"`
	Total  int     `json:"total"`
}

// OrderStatus defines model for OrderStatus.
type OrderStatus string

// OrdersByStatusEntry defines model for OrdersByStatusEntry.
type OrdersByStatusEntry struct {
	Count  int         `json:"count"`
	Status OrderStatus `json:"status"`
}

// PairingAxis Ось pairing-тега:
// - drink — с каким напитком сочетается;
// - occasion — для какого повода;
// - role — слот в трапезе (аперитив/основное/гарнир/финал);
// - vibe — настроение / плотность / температура.
type PairingAxis string

// PairingTag defines model for PairingTag.
type PairingTag struct {
	// Axis Ось pairing-тега:
	// - drink — с каким напитком сочетается;
	// - occasion — для какого повода;
	// - role — слот в трапезе (аперитив/основное/гарнир/финал);
	// - vibe — настроение / плотность / температура.
	Axis PairingAxis `json:"axis"`

	// EmbedPhrase Фраза в embed-тексте блюда («белому вину»)
	EmbedPhrase string `json:"embed_phrase"`

	// IsActive Если false — тег нельзя присваивать, но уже привязанные остаются
	IsActive bool `json:"is_active"`

	// Label Человекочитаемая метка для админ UI
	Label string `json:"label"`

	// Slug Машинный идентификатор (PK)
	Slug string `json:"slug"`

	// SortOrder Порядок в админ UI внутри оси
	SortOrder int `json:"sort_order"`
}

// PairingTagList defines model for PairingTagList.
type PairingTagList struct {
	Items []PairingTag `json:"items"`
}

// PatchCartItemRequest defines model for PatchCartItemRequest.
type PatchCartItemRequest struct {
	Note      *string `json:"note,omitempty"`
	Quantity  *int    `json:"quantity,omitempty"`
	SortOrder *int    `json:"sort_order,omitempty"`
}

// PatchCategoryRequest defines model for PatchCategoryRequest.
type PatchCategoryRequest struct {
	IsAvailable *bool   `json:"is_available,omitempty"`
	Name        *string `json:"name,omitempty"`

	// Role Роль категории в RAG-пайплайне рекомендаций:
	// * `none`      — не участвует в diversify/companion-логике;
	// * `main`      — основная категория, для диверсификации main-выдачи;
	// * `companion` — сопровождение (соус/гарнир/десерт/напиток), по 1 блюду на запрос.
	Role      *CategoryRole `json:"role,omitempty"`
	SortOrder *int          `json:"sort_order,omitempty"`
}

// PatchChatSuggestionRequest defines model for PatchChatSuggestionRequest.
type PatchChatSuggestionRequest struct {
	IsActive  *bool   `json:"is_active,omitempty"`
	SortOrder *int    `json:"sort_order,omitempty"`
	Text      *string `json:"text,omitempty"`
}

// PatchDishRequest defines model for PatchDishRequest.
type PatchDishRequest struct {
	Allergens    *[]string `json:"allergens,omitempty"`
	CaloriesKcal *int      `json:"calories_kcal,omitempty"`
	CarbsG       *float32  `json:"carbs_g,omitempty"`
	CategoryId   *int      `json:"category_id,omitempty"`
	Composition  *string   `json:"composition,omitempty"`
	Cuisine      *Cuisine  `json:"cuisine,omitempty"`
	Currency     *string   `json:"currency,omitempty"`
	Description  *string   `json:"description,omitempty"`
	Dietary      *[]string `json:"dietary,omitempty"`
	FatG         *float32  `json:"fat_g,omitempty"`
	ImageUrl     *string   `json:"image_url,omitempty"`
	IsAvailable  *bool     `json:"is_available,omitempty"`
	Name         *string   `json:"name,omitempty"`

	// PairingTagSlugs Slug'и pairing-тегов; nil — не менять связи, [] — очистить все
	PairingTagSlugs *[]string `json:"pairing_tag_slugs,omitempty"`
	PortionWeightG  *int      `json:"portion_weight_g,omitempty"`
	PriceMinor      *int      `json:"price_minor,omitempty"`
	ProteinG        *float32  `json:"protein_g,omitempty"`
	TagIds          *[]int    `json:"tag_ids,omitempty"`
}

// PatchOrderStatusRequest defines model for PatchOrderStatusRequest.
type PatchOrderStatusRequest struct {
	Note   *string     `json:"note,omitempty"`
	Status OrderStatus `json:"status"`
}

// PatchProfileRequest defines model for PatchProfileRequest.
type PatchProfileRequest struct {
	Allergens *[]string `json:"allergens,omitempty"`
	Dietary   *[]string `json:"dietary,omitempty"`
	FirstName *string   `json:"first_name,omitempty"`
	LastName  *string   `json:"last_name,omitempty"`
	Phone     *string   `json:"phone,omitempty"`
}

// PatchTagRequest defines model for PatchTagRequest.
type PatchTagRequest struct {
	Color *string `json:"color,omitempty"`
	Name  *string `json:"name,omitempty"`
	Slug  *string `json:"slug,omitempty"`
}

// PaymentMethod defines model for PaymentMethod.
type PaymentMethod string

// Profile defines model for Profile.
type Profile struct {
	// Allergens allergen codes
	Allergens []string `json:"allergens"`

	// Dietary dietary codes
	Dietary   []string            `json:"dietary"`
	Email     openapi_types.Email `json:"email"`
	FirstName *string             `json:"first_name,omitempty"`
	LastName  *string             `json:"last_name,omitempty"`

	// Phone E.164
	Phone *string `json:"phone,omitempty"`
}

// Prompt defines model for Prompt.
type Prompt struct {
	Current PromptVersion `json:"current"`
	Draft   *PromptDraft  `json:"draft,omitempty"`

	// Name Имя промпта. Валидные значения определены в коде (prompts.SupportedNames).
	Name PromptName `json:"name"`
}

// PromptAuthor defines model for PromptAuthor.
type PromptAuthor struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
}

// PromptDetails defines model for PromptDetails.
type PromptDetails struct {
	Current PromptVersion `json:"current"`
	Draft   *PromptDraft  `json:"draft,omitempty"`

	// History Все версии (включая active) в порядке убывания version
	History []PromptVersion `json:"history"`

	// Name Имя промпта. Валидные значения определены в коде (prompts.SupportedNames).
	Name PromptName `json:"name"`
}

// PromptDraft defines model for PromptDraft.
type PromptDraft struct {
	Content string `json:"content"`

	// Name Имя промпта. Валидные значения определены в коде (prompts.SupportedNames).
	Name      PromptName `json:"name"`
	UpdatedAt time.Time  `json:"updated_at"`
}

// PromptList defines model for PromptList.
type PromptList struct {
	Items []Prompt `json:"items"`
}

// PromptName Имя промпта. Валидные значения определены в коде (prompts.SupportedNames).
type PromptName = string

// PromptVersion defines model for PromptVersion.
type PromptVersion struct {
	Content     string       `json:"content"`
	PublishedAt time.Time    `json:"published_at"`
	PublishedBy PromptAuthor `json:"published_by"`
	Version     int          `json:"version"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// ReindexAllDishesRequest defines model for ReindexAllDishesRequest.
type ReindexAllDishesRequest struct {
	// IncludeUnavailable Включать ли блюда с is_available=false (нужно, если хочешь иметь embedding под будущее переключение)
	IncludeUnavailable *bool `json:"include_unavailable,omitempty"`
}

// SendMessageRequest defines model for SendMessageRequest.
type SendMessageRequest struct {
	Content string `json:"content"`
}

// SessionInfo defines model for SessionInfo.
type SessionInfo struct {
	Csrf    string           `json:"csrf"`
	IsGuest bool             `json:"is_guest"`
	Role    *SessionInfoRole `json:"role,omitempty"`

	// UserId null если ещё не было стейтфул-действий — PG-строки пользователя пока нет
	UserId *openapi_types.UUID `json:"user_id,omitempty"`
}

// SessionInfoRole defines model for SessionInfo.Role.
type SessionInfoRole string

// Tag defines model for Tag.
type Tag struct {
	// Color hex, например #E53935
	Color string `json:"color"`
	Id    int    `json:"id"`
	Name  string `json:"name"`
	Slug  string `json:"slug"`
}

// TagList defines model for TagList.
type TagList struct {
	Items []Tag `json:"items"`
}

// TopDishEntry defines model for TopDishEntry.
type TopDishEntry struct {
	DishId   int    `json:"dish_id"`
	DishName string `json:"dish_name"`

	// Value значение метрики (заказано / рекомендовано)
	Value int `json:"value"`
}

// UpsertPromptDraftRequest defines model for UpsertPromptDraftRequest.
type UpsertPromptDraftRequest struct {
	Content string `json:"content"`
}

// CSRFToken defines model for CSRFToken.
type CSRFToken = string

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// PathDishID defines model for PathDishID.
type PathDishID = int

// PathID defines model for PathID.
type PathID = openapi_types.UUID

// PathIntID defines model for PathIntID.
type PathIntID = int

// QueryPromptName defines model for QueryPromptName.
type QueryPromptName = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// AdminListActionsParams defines parameters for AdminListActions.
type AdminListActionsParams struct {
	// AdminId uuid админа или строка 'me'
	AdminId *string                       `form:"admin_id,omitempty" json:"admin_id,omitempty"`
	Target  *AdminListActionsParamsTarget `form:"target,omitempty" json:"target,omitempty"`
	From    *time.Time                    `form:"from,omitempty" json:"from,omitempty"`
	To      *time.Time                    `form:"to,omitempty" json:"to,omitempty"`
	Limit   *Limit                        `form:"limit,omitempty" json:"limit,omitempty"`
	Offset  *Offset                       `form:"offset,omitempty" json:"offset,omitempty"`
}

// AdminListActionsParamsTarget defines parameters for AdminListActions.
type AdminListActionsParamsTarget string

// AdminGetAnalyticsParams defines parameters for AdminGetAnalytics.
type AdminGetAnalyticsParams struct {
	Period AdminGetAnalyticsParamsPeriod `form:"period" json:"period"`
}

// AdminGetAnalyticsParamsPeriod defines parameters for AdminGetAnalytics.
type AdminGetAnalyticsParamsPeriod string

// AdminCreateCategoryParams defines parameters for AdminCreateCategory.
type AdminCreateCategoryParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminDeleteCategoryParams defines parameters for AdminDeleteCategory.
type AdminDeleteCategoryParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminUpdateCategoryParams defines parameters for AdminUpdateCategory.
type AdminUpdateCategoryParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminGetDashboardParams defines parameters for AdminGetDashboard.
type AdminGetDashboardParams struct {
	Period AdminGetDashboardParamsPeriod `form:"period" json:"period"`
}

// AdminGetDashboardParamsPeriod defines parameters for AdminGetDashboard.
type AdminGetDashboardParamsPeriod string

// AdminDebugSearchByQueryParams defines parameters for AdminDebugSearchByQuery.
type AdminDebugSearchByQueryParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminCreateDishParams defines parameters for AdminCreateDish.
type AdminCreateDishParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminReindexAllDishesParams defines parameters for AdminReindexAllDishes.
type AdminReindexAllDishesParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminDeleteDishParams defines parameters for AdminDeleteDish.
type AdminDeleteDishParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminUpdateDishParams defines parameters for AdminUpdateDish.
type AdminUpdateDishParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminPreviewDishEmbeddingParams defines parameters for AdminPreviewDishEmbedding.
type AdminPreviewDishEmbeddingParams struct {
	// Neighbors Сколько ближайших точек вернуть (по умолчанию 10)
	Neighbors *int `form:"neighbors,omitempty" json:"neighbors,omitempty"`
}

// AdminUploadDishImageMultipartBody defines parameters for AdminUploadDishImage.
type AdminUploadDishImageMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// AdminUploadDishImageParams defines parameters for AdminUploadDishImage.
type AdminUploadDishImageParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminReindexDishParams defines parameters for AdminReindexDish.
type AdminReindexDishParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminListOrdersParams defines parameters for AdminListOrders.
type AdminListOrdersParams struct {
	Status *OrderStatus        `form:"status,omitempty" json:"status,omitempty"`
	From   *time.Time          `form:"from,omitempty" json:"from,omitempty"`
	To     *time.Time          `form:"to,omitempty" json:"to,omitempty"`
	UserId *openapi_types.UUID `form:"user_id,omitempty" json:"user_id,omitempty"`
	Limit  *Limit              `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset             `form:"offset,omitempty" json:"offset,omitempty"`
}

// AdminListOrderActionsParams defines parameters for AdminListOrderActions.
type AdminListOrderActionsParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// AdminUpdateOrderStatusParams defines parameters for AdminUpdateOrderStatus.
type AdminUpdateOrderStatusParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminGetPromptParams defines parameters for AdminGetPrompt.
type AdminGetPromptParams struct {
	// Name Имя промпта. Список валидных имён задан в коде (prompts.SupportedNames).
	// Сейчас: system, classification, refusal. Расширение — без правки OpenAPI,
	// проверка идёт в usecase через prompts.IsSupported.
	Name QueryPromptName `form:"name" json:"name"`
}

// AdminDeletePromptDraftParams defines parameters for AdminDeletePromptDraft.
type AdminDeletePromptDraftParams struct {
	// Name Имя промпта. Список валидных имён задан в коде (prompts.SupportedNames).
	// Сейчас: system, classification, refusal. Расширение — без правки OpenAPI,
	// проверка идёт в usecase через prompts.IsSupported.
	Name       QueryPromptName `form:"name" json:"name"`
	XCSRFToken CSRFToken       `json:"X-CSRF-Token"`
}

// AdminUpsertPromptDraftParams defines parameters for AdminUpsertPromptDraft.
type AdminUpsertPromptDraftParams struct {
	// Name Имя промпта. Список валидных имён задан в коде (prompts.SupportedNames).
	// Сейчас: system, classification, refusal. Расширение — без правки OpenAPI,
	// проверка идёт в usecase через prompts.IsSupported.
	Name       QueryPromptName `form:"name" json:"name"`
	XCSRFToken CSRFToken       `json:"X-CSRF-Token"`
}

// AdminPublishPromptParams defines parameters for AdminPublishPrompt.
type AdminPublishPromptParams struct {
	// Name Имя промпта. Список валидных имён задан в коде (prompts.SupportedNames).
	// Сейчас: system, classification, refusal. Расширение — без правки OpenAPI,
	// проверка идёт в usecase через prompts.IsSupported.
	Name       QueryPromptName `form:"name" json:"name"`
	XCSRFToken CSRFToken       `json:"X-CSRF-Token"`
}

// AdminRollbackPromptParams defines parameters for AdminRollbackPrompt.
type AdminRollbackPromptParams struct {
	// Name Имя промпта. Список валидных имён задан в коде (prompts.SupportedNames).
	// Сейчас: system, classification, refusal. Расширение — без правки OpenAPI,
	// проверка идёт в usecase через prompts.IsSupported.
	Name       QueryPromptName `form:"name" json:"name"`
	Version    int             `form:"version" json:"version"`
	XCSRFToken CSRFToken       `json:"X-CSRF-Token"`
}

// AdminCreateChatSuggestionParams defines parameters for AdminCreateChatSuggestion.
type AdminCreateChatSuggestionParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminDeleteChatSuggestionParams defines parameters for AdminDeleteChatSuggestion.
type AdminDeleteChatSuggestionParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminUpdateChatSuggestionParams defines parameters for AdminUpdateChatSuggestion.
type AdminUpdateChatSuggestionParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminCreateTagParams defines parameters for AdminCreateTag.
type AdminCreateTagParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminDeleteTagParams defines parameters for AdminDeleteTag.
type AdminDeleteTagParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminUpdateTagParams defines parameters for AdminUpdateTag.
type AdminUpdateTagParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// LoginParams defines parameters for Login.
type LoginParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// LogoutParams defines parameters for Logout.
type LogoutParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ChangePasswordParams defines parameters for ChangePassword.
type ChangePasswordParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// RegisterParams defines parameters for Register.
type RegisterParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ClearCartParams defines parameters for ClearCart.
type ClearCartParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AddCartItemParams defines parameters for AddCartItem.
type AddCartItemParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// RemoveCartItemParams defines parameters for RemoveCartItem.
type RemoveCartItemParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// UpdateCartItemParams defines parameters for UpdateCartItem.
type UpdateCartItemParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// TrackChatSuggestionClickParams defines parameters for TrackChatSuggestionClick.
type TrackChatSuggestionClickParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListChatsParams defines parameters for ListChats.
type ListChatsParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateChatParams defines parameters for CreateChat.
type CreateChatParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// DeleteChatParams defines parameters for DeleteChat.
type DeleteChatParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// GetChatParams defines parameters for GetChat.
type GetChatParams struct {
	MessagesLimit *int `form:"messages_limit,omitempty" json:"messages_limit,omitempty"`

	// MessagesBefore cursor — id сообщения, до которого подгружаем
	MessagesBefore *openapi_types.UUID `form:"messages_before,omitempty" json:"messages_before,omitempty"`
}

// SendMessageParams defines parameters for SendMessage.
type SendMessageParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListDishesParams defines parameters for ListDishes.
type ListDishesParams struct {
	CategoryId *int `form:"category_id,omitempty" json:"category_id,omitempty"`

	// Available по умолчанию true; false вернёт всё включая стоп-лист
	Available *bool `form:"available,omitempty" json:"available,omitempty"`

	// Q поиск по названию
	Q                *string   `form:"q,omitempty" json:"q,omitempty"`
	ExcludeAllergens *[]string `form:"exclude_allergens,omitempty" json:"exclude_allergens,omitempty"`
	Dietary          *[]string `form:"dietary,omitempty" json:"dietary,omitempty"`
	TagIds           *[]int    `form:"tag_ids,omitempty" json:"tag_ids,omitempty"`
	Limit            *Limit    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset           *Offset   `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListOrdersParams defines parameters for ListOrders.
type ListOrdersParams struct {
	Status *OrderStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *Limit       `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset      `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateOrderParams defines parameters for CreateOrder.
type CreateOrderParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// UpdateProfileParams defines parameters for UpdateProfile.
type UpdateProfileParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AdminCreateCategoryJSONRequestBody defines body for AdminCreateCategory for application/json ContentType.
type AdminCreateCategoryJSONRequestBody = CreateCategoryRequest

// AdminUpdateCategoryJSONRequestBody defines body for AdminUpdateCategory for application/json ContentType.
type AdminUpdateCategoryJSONRequestBody = PatchCategoryRequest

// AdminDebugSearchByQueryJSONRequestBody defines body for AdminDebugSearchByQuery for application/json ContentType.
type AdminDebugSearchByQueryJSONRequestBody = DebugSearchRequest

// AdminCreateDishJSONRequestBody defines body for AdminCreateDish for application/json ContentType.
type AdminCreateDishJSONRequestBody = CreateDishRequest

// AdminReindexAllDishesJSONRequestBody defines body for AdminReindexAllDishes for application/json ContentType.
type AdminReindexAllDishesJSONRequestBody = ReindexAllDishesRequest

// AdminUpdateDishJSONRequestBody defines body for AdminUpdateDish for application/json ContentType.
type AdminUpdateDishJSONRequestBody = PatchDishRequest

// AdminUploadDishImageMultipartRequestBody defines body for AdminUploadDishImage for multipart/form-data ContentType.
type AdminUploadDishImageMultipartRequestBody AdminUploadDishImageMultipartBody

// AdminUpdateOrderStatusJSONRequestBody defines body for AdminUpdateOrderStatus for application/json ContentType.
type AdminUpdateOrderStatusJSONRequestBody = PatchOrderStatusRequest

// AdminUpsertPromptDraftJSONRequestBody defines body for AdminUpsertPromptDraft for application/json ContentType.
type AdminUpsertPromptDraftJSONRequestBody = UpsertPromptDraftRequest

// AdminCreateChatSuggestionJSONRequestBody defines body for AdminCreateChatSuggestion for application/json ContentType.
type AdminCreateChatSuggestionJSONRequestBody = CreateChatSuggestionRequest

// AdminUpdateChatSuggestionJSONRequestBody defines body for AdminUpdateChatSuggestion for application/json ContentType.
type AdminUpdateChatSuggestionJSONRequestBody = PatchChatSuggestionRequest

// AdminCreateTagJSONRequestBody defines body for AdminCreateTag for application/json ContentType.
type AdminCreateTagJSONRequestBody = CreateTagRequest

// AdminUpdateTagJSONRequestBody defines body for AdminUpdateTag for application/json ContentType.
type AdminUpdateTagJSONRequestBody = PatchTagRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// AddCartItemJSONRequestBody defines body for AddCartItem for application/json ContentType.
type AddCartItemJSONRequestBody = AddCartItemRequest

// UpdateCartItemJSONRequestBody defines body for UpdateCartItem for application/json ContentType.
type UpdateCartItemJSONRequestBody = PatchCartItemRequest

// CreateChatJSONRequestBody defines body for CreateChat for application/json ContentType.
type CreateChatJSONRequestBody = CreateChatRequest

// SendMessageJSONRequestBody defines body for SendMessage for application/json ContentType.
type SendMessageJSONRequestBody = SendMessageRequest

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrderRequest

// UpdateProfileJSONRequestBody defines body for UpdateProfile for application/json ContentType.
type UpdateProfileJSONRequestBody = PatchProfileRequest

// Getter for additional properties for Error_Error_Details. Returns the specified
// element and whether it was found
func (a Error_Error_Details) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Error_Error_Details
func (a *Error_Error_Details) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Error_Error_Details to handle AdditionalProperties
func (a *Error_Error_Details) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["fields"]; found {
		err = json.Unmarshal(raw, &a.Fields)
		if err != nil {
			return fmt.Errorf("error reading 'fields': %w", err)
		}
		delete(object, "fields")
	}

	if raw, found := object["trace_id"]; found {
		err = json.Unmarshal(raw, &a.TraceId)
		if err != nil {
			return fmt.Errorf("error reading 'trace_id': %w", err)
		}
		delete(object, "trace_id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Error_Error_Details to handle AdditionalProperties
func (a Error_Error_Details) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Fields != nil {
		object["fields"], err = json.Marshal(a.Fields)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fields': %w", err)
		}
	}

	if a.TraceId != nil {
		object["trace_id"], err = json.Marshal(a.TraceId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'trace_id': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsFieldViolationMax0 returns the union data inside the FieldViolation_Max as a FieldViolationMax0
func (t FieldViolation_Max) AsFieldViolationMax0() (FieldViolationMax0, error) {
	var body FieldViolationMax0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFieldViolationMax0 overwrites any union data inside the FieldViolation_Max as the provided FieldViolationMax0
func (t *FieldViolation_Max) FromFieldViolationMax0(v FieldViolationMax0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFieldViolationMax0 performs a merge with any union data inside the FieldViolation_Max, using the provided FieldViolationMax0
func (t *FieldViolation_Max) MergeFieldViolationMax0(v FieldViolationMax0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFieldViolationMax1 returns the union data inside the FieldViolation_Max as a FieldViolationMax1
func (t FieldViolation_Max) AsFieldViolationMax1() (FieldViolationMax1, error) {
	var body FieldViolationMax1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFieldViolationMax1 overwrites any union data inside the FieldViolation_Max as the provided FieldViolationMax1
func (t *FieldViolation_Max) FromFieldViolationMax1(v FieldViolationMax1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFieldViolationMax1 performs a merge with any union data inside the FieldViolation_Max, using the provided FieldViolationMax1
func (t *FieldViolation_Max) MergeFieldViolationMax1(v FieldViolationMax1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFieldViolationMax2 returns the union data inside the FieldViolation_Max as a FieldViolationMax2
func (t FieldViolation_Max) AsFieldViolationMax2() (FieldViolationMax2, error) {
	var body FieldViolationMax2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFieldViolationMax2 overwrites any union data inside the FieldViolation_Max as the provided FieldViolationMax2
func (t *FieldViolation_Max) FromFieldViolationMax2(v FieldViolationMax2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFieldViolationMax2 performs a merge with any union data inside the FieldViolation_Max, using the provided FieldViolationMax2
func (t *FieldViolation_Max) MergeFieldViolationMax2(v FieldViolationMax2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t FieldViolation_Max) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *FieldViolation_Max) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsFieldViolationMin0 returns the union data inside the FieldViolation_Min as a FieldViolationMin0
func (t FieldViolation_Min) AsFieldViolationMin0() (FieldViolationMin0, error) {
	var body FieldViolationMin0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFieldViolationMin0 overwrites any union data inside the FieldViolation_Min as the provided FieldViolationMin0
func (t *FieldViolation_Min) FromFieldViolationMin0(v FieldViolationMin0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFieldViolationMin0 performs a merge with any union data inside the FieldViolation_Min, using the provided FieldViolationMin0
func (t *FieldViolation_Min) MergeFieldViolationMin0(v FieldViolationMin0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFieldViolationMin1 returns the union data inside the FieldViolation_Min as a FieldViolationMin1
func (t FieldViolation_Min) AsFieldViolationMin1() (FieldViolationMin1, error) {
	var body FieldViolationMin1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFieldViolationMin1 overwrites any union data inside the FieldViolation_Min as the provided FieldViolationMin1
func (t *FieldViolation_Min) FromFieldViolationMin1(v FieldViolationMin1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFieldViolationMin1 performs a merge with any union data inside the FieldViolation_Min, using the provided FieldViolationMin1
func (t *FieldViolation_Min) MergeFieldViolationMin1(v FieldViolationMin1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFieldViolationMin2 returns the union data inside the FieldViolation_Min as a FieldViolationMin2
func (t FieldViolation_Min) AsFieldViolationMin2() (FieldViolationMin2, error) {
	var body FieldViolationMin2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFieldViolationMin2 overwrites any union data inside the FieldViolation_Min as the provided FieldViolationMin2
func (t *FieldViolation_Min) FromFieldViolationMin2(v FieldViolationMin2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFieldViolationMin2 performs a merge with any union data inside the FieldViolation_Min, using the provided FieldViolationMin2
func (t *FieldViolation_Min) MergeFieldViolationMin2(v FieldViolationMin2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t FieldViolation_Min) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *FieldViolation_Min) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
